#ifndef NXDK_HAVE_D3D8TYPES
#define NXDK_HAVE_D3D8TYPES 1

#include <windows.h>
#include <winnt.h>

typedef HANDLE HMONITOR;

typedef struct _GUID {
    unsigned long  Data1;
    unsigned short Data2;
    unsigned short Data3;
    unsigned char  Data4[8];
} GUID;

#define _FACD3D  0x876
#define MAKE_D3DHRESULT(code)  MAKE_HRESULT(1, _FACD3D, code)

#define D3D_OK                                  S_OK

#define D3DERR_WRONGTEXTUREFORMAT               MAKE_D3DHRESULT(2072)
#define D3DERR_UNSUPPORTEDCOLOROPERATION        MAKE_D3DHRESULT(2073)
#define D3DERR_UNSUPPORTEDCOLORARG              MAKE_D3DHRESULT(2074)
#define D3DERR_UNSUPPORTEDALPHAOPERATION        MAKE_D3DHRESULT(2075)
#define D3DERR_UNSUPPORTEDALPHAARG              MAKE_D3DHRESULT(2076)
#define D3DERR_TOOMANYOPERATIONS                MAKE_D3DHRESULT(2077)
#define D3DERR_CONFLICTINGTEXTUREFILTER         MAKE_D3DHRESULT(2078)
#define D3DERR_UNSUPPORTEDFACTORVALUE           MAKE_D3DHRESULT(2079)
#define D3DERR_CONFLICTINGRENDERSTATE           MAKE_D3DHRESULT(2081)
#define D3DERR_UNSUPPORTEDTEXTUREFILTER         MAKE_D3DHRESULT(2082)
#define D3DERR_CONFLICTINGTEXTUREPALETTE        MAKE_D3DHRESULT(2086)
#define D3DERR_DRIVERINTERNALERROR              MAKE_D3DHRESULT(2087)
#define D3DERR_TESTINCOMPLETE                   MAKE_D3DHRESULT(2088)
#define D3DERR_BUFFERTOOSMALL                   MAKE_D3DHRESULT(2089)
#define D3DERR_TIMEEXPIRED                      MAKE_D3DHRESULT(2090)

#define D3DERR_NOTFOUND                         MAKE_D3DHRESULT(2150)
#define D3DERR_MOREDATA                         MAKE_D3DHRESULT(2151)
#define D3DERR_DEVICELOST                       MAKE_D3DHRESULT(2152)
#define D3DERR_DEVICENOTRESET                   MAKE_D3DHRESULT(2153)
#define D3DERR_NOTAVAILABLE                     MAKE_D3DHRESULT(2154)
#define D3DERR_OUTOFVIDEOMEMORY                 MAKE_D3DHRESULT(380)
#define D3DERR_INVALIDDEVICE                    MAKE_D3DHRESULT(2155)
#define D3DERR_INVALIDCALL                      MAKE_D3DHRESULT(2156)

#define D3DCREATE_FPU_PRESERVE                  0x00000002L
#define D3DCREATE_MULTITHREADED                 0x00000004L

#define D3DCREATE_PUREDEVICE                    0x00000010L
#define D3DCREATE_SOFTWARE_VERTEXPROCESSING     0x00000020L
#define D3DCREATE_HARDWARE_VERTEXPROCESSING     0x00000040L
#define D3DCREATE_MIXED_VERTEXPROCESSING        0x00000080L

#define MAX_DEVICE_IDENTIFIER_STRING 512
typedef struct _D3DADAPTER_IDENTIFIER8 {
    char            Driver     [MAX_DEVICE_IDENTIFIER_STRING];
    char            Description[MAX_DEVICE_IDENTIFIER_STRING];

    LARGE_INTEGER   DriverVersion;            /* Defined for 32 bit components */

    DWORD           VendorId;
    DWORD           DeviceId;
    DWORD           SubSysId;
    DWORD           Revision;

    GUID            DeviceIdentifier;

    DWORD           WHQLLevel;
} D3DADAPTER_IDENTIFIER8;

#define MAKEFOURCC(ch0, ch1, ch2, ch3)                                \
            ((DWORD)(BYTE)(ch0) | ((DWORD)(BYTE)(ch1) << 8) |         \
            ((DWORD)(BYTE)(ch2) << 16) | ((DWORD)(BYTE)(ch3) << 24 ))

typedef enum _D3DFORMAT {
    D3DFMT_UNKNOWN      = 0xFFFFFFFF,

    D3DFMT_A8R8G8B8     = NV097_SET_TEXTURE_FORMAT_COLOR_SZ_A8R8G8B8,
    D3DFMT_X8R8G8B8     = NV097_SET_TEXTURE_FORMAT_COLOR_SZ_X8R8G8B8,
    D3DFMT_R5G6B5       = NV097_SET_TEXTURE_FORMAT_COLOR_SZ_R5G6B5,
    D3DFMT_R6G5B5       = NV097_SET_TEXTURE_FORMAT_COLOR_SZ_R6G5B5,
    D3DFMT_X1R5G5B5     = NV097_SET_TEXTURE_FORMAT_COLOR_SZ_X1R5G5B5,
    D3DFMT_A1R5G5B5     = NV097_SET_TEXTURE_FORMAT_COLOR_SZ_A1R5G5B5,
    D3DFMT_A4R4G4B4     = NV097_SET_TEXTURE_FORMAT_COLOR_SZ_A4R4G4B4,
    D3DFMT_A8           = NV097_SET_TEXTURE_FORMAT_COLOR_SZ_A8,
    D3DFMT_A8B8G8R8     = NV097_SET_TEXTURE_FORMAT_COLOR_SZ_A8B8G8R8,
    D3DFMT_B8G8R8A8     = NV097_SET_TEXTURE_FORMAT_COLOR_SZ_B8G8R8A8,
    D3DFMT_R4G4B4A4     = NV097_SET_TEXTURE_FORMAT_COLOR_SZ_R4G4B4A4,
    D3DFMT_R5G5B5A1     = NV097_SET_TEXTURE_FORMAT_COLOR_SZ_R5G5B5A1,
    D3DFMT_R8G8B8A8     = NV097_SET_TEXTURE_FORMAT_COLOR_SZ_R8G8B8A8,
    D3DFMT_R8B8         = NV097_SET_TEXTURE_FORMAT_COLOR_SZ_R8B8,
    D3DFMT_G8B8         = NV097_SET_TEXTURE_FORMAT_COLOR_SZ_G8B8,

    D3DFMT_P8           = NV097_SET_TEXTURE_FORMAT_COLOR_SZ_I8_A8R8G8B8,

    D3DFMT_L8           = NV097_SET_TEXTURE_FORMAT_COLOR_SZ_Y8,
    D3DFMT_A8L8         = NV097_SET_TEXTURE_FORMAT_COLOR_SZ_A8Y8,
    D3DFMT_AL8          = NV097_SET_TEXTURE_FORMAT_COLOR_SZ_AY8,
    D3DFMT_L16          = NV097_SET_TEXTURE_FORMAT_COLOR_LU_IMAGE_DEPTH_Y16,

    D3DFMT_V8U8         = NV097_SET_TEXTURE_FORMAT_COLOR_SZ_G8B8,
    D3DFMT_L6V5U5       = NV097_SET_TEXTURE_FORMAT_COLOR_SZ_R6G5B5,
    D3DFMT_X8L8V8U8     = NV097_SET_TEXTURE_FORMAT_COLOR_SZ_X8R8G8B8,
    D3DFMT_Q8W8V8U8     = NV097_SET_TEXTURE_FORMAT_COLOR_SZ_A8B8G8R8,
    D3DFMT_V16U16       = NV097_SET_TEXTURE_FORMAT_COLOR_SZ_G16B16,

    D3DFMT_D16_LOCKABLE = NV097_SET_TEXTURE_FORMAT_COLOR_SZ_DEPTH_Y16_FIXED,
    D3DFMT_D16          = NV097_SET_TEXTURE_FORMAT_COLOR_SZ_DEPTH_Y16_FIXED,
    D3DFMT_D24S8        = NV097_SET_TEXTURE_FORMAT_COLOR_SZ_DEPTH_X8_Y24_FIXED,
    D3DFMT_F16          = NV097_SET_TEXTURE_FORMAT_COLOR_SZ_DEPTH_Y16_FLOAT,
    D3DFMT_F24S8        = NV097_SET_TEXTURE_FORMAT_COLOR_SZ_DEPTH_X8_Y24_FLOAT,

    D3DFMT_YUY2         = NV097_SET_TEXTURE_FORMAT_COLOR_LC_IMAGE_CR8YB8CB8YA8,
    D3DFMT_UYVY         = NV097_SET_TEXTURE_FORMAT_COLOR_LC_IMAGE_YB8CR8YA8CB8,

    D3DFMT_DXT1         = NV097_SET_TEXTURE_FORMAT_COLOR_L_DXT1_A1R5G5B5,
    D3DFMT_DXT2         = NV097_SET_TEXTURE_FORMAT_COLOR_L_DXT23_A8R8G8B8,
    D3DFMT_DXT3         = NV097_SET_TEXTURE_FORMAT_COLOR_L_DXT23_A8R8G8B8,
    D3DFMT_DXT4         = NV097_SET_TEXTURE_FORMAT_COLOR_L_DXT45_A8R8G8B8,
    D3DFMT_DXT5         = NV097_SET_TEXTURE_FORMAT_COLOR_L_DXT45_A8R8G8B8,

    D3DFMT_LIN_A1R5G5B5 = NV097_SET_TEXTURE_FORMAT_COLOR_LU_IMAGE_A1R5G5B5,
    D3DFMT_LIN_A4R4G4B4 = NV097_SET_TEXTURE_FORMAT_COLOR_LU_IMAGE_A4R4G4B4,
    D3DFMT_LIN_A8       = NV097_SET_TEXTURE_FORMAT_COLOR_LU_IMAGE_A8,
    D3DFMT_LIN_A8B8G8R8 = NV097_SET_TEXTURE_FORMAT_COLOR_LU_IMAGE_A8B8G8R8,
    D3DFMT_LIN_A8R8G8B8 = NV097_SET_TEXTURE_FORMAT_COLOR_LU_IMAGE_A8R8G8B8,
    D3DFMT_LIN_B8G8R8A8 = NV097_SET_TEXTURE_FORMAT_COLOR_LU_IMAGE_B8G8R8A8,
    D3DFMT_LIN_G8B8     = NV097_SET_TEXTURE_FORMAT_COLOR_LU_IMAGE_G8B8,
    D3DFMT_LIN_R4G4B4A4 = NV097_SET_TEXTURE_FORMAT_COLOR_LU_IMAGE_R4G4B4A4,
    D3DFMT_LIN_R5G5B5A1 = NV097_SET_TEXTURE_FORMAT_COLOR_LU_IMAGE_R5G5B5A1,
    D3DFMT_LIN_R5G6B5   = NV097_SET_TEXTURE_FORMAT_COLOR_LU_IMAGE_R5G6B5,
    D3DFMT_LIN_R6G5B5   = NV097_SET_TEXTURE_FORMAT_COLOR_SZ_R6G5B5,
    D3DFMT_LIN_R8B8     = NV097_SET_TEXTURE_FORMAT_COLOR_LU_IMAGE_R8B8,
    D3DFMT_LIN_R8G8B8A8 = NV097_SET_TEXTURE_FORMAT_COLOR_LU_IMAGE_R8G8B8A8,
    D3DFMT_LIN_X1R5G5B5 = NV097_SET_TEXTURE_FORMAT_COLOR_LU_IMAGE_X1R5G5B5,
    D3DFMT_LIN_X8R8G8B8 = NV097_SET_TEXTURE_FORMAT_COLOR_LU_IMAGE_X8R8G8B8,

    D3DFMT_LIN_A8L8     = NV097_SET_TEXTURE_FORMAT_COLOR_LU_IMAGE_A8Y8,
    D3DFMT_LIN_AL8      = NV097_SET_TEXTURE_FORMAT_COLOR_LU_IMAGE_AY8,
    D3DFMT_LIN_L16      = NV097_SET_TEXTURE_FORMAT_COLOR_LU_IMAGE_Y16,
    D3DFMT_LIN_L8       = NV097_SET_TEXTURE_FORMAT_COLOR_LU_IMAGE_Y8,

    D3DFMT_LIN_V16U16   = NV097_SET_TEXTURE_FORMAT_COLOR_SZ_G16B16,
    D3DFMT_LIN_V8U8     = NV097_SET_TEXTURE_FORMAT_COLOR_LU_IMAGE_G8B8,
    D3DFMT_LIN_L6V5U5   = NV097_SET_TEXTURE_FORMAT_COLOR_SZ_R6G5B5,
    D3DFMT_LIN_X8L8V8U8 = NV097_SET_TEXTURE_FORMAT_COLOR_LU_IMAGE_X8R8G8B8,
    D3DFMT_LIN_Q8W8V8U8 = NV097_SET_TEXTURE_FORMAT_COLOR_LU_IMAGE_A8B8G8R8,

    D3DFMT_LIN_D24S8 = 
        NV097_SET_TEXTURE_FORMAT_COLOR_LU_IMAGE_DEPTH_X8_Y24_FIXED,
    D3DFMT_LIN_F24S8 = 
        NV097_SET_TEXTURE_FORMAT_COLOR_LU_IMAGE_DEPTH_X8_Y24_FLOAT,
    D3DFMT_LIN_D16 = NV097_SET_TEXTURE_FORMAT_COLOR_LU_IMAGE_DEPTH_Y16_FIXED,
    D3DFMT_LIN_F16 = NV097_SET_TEXTURE_FORMAT_COLOR_LU_IMAGE_DEPTH_Y16_FLOAT,

    D3DFMT_VERTEXDATA   = 100, // Arbitrary constants,
    D3DFMT_INDEX16      = 101, // not used by the hardware.

    D3DFMT_FORCE_DWORD  =0x7fffffff
} D3DFORMAT;

#define D3DPRESENTFLAG_LOCKABLE_BACKBUFFER   0x00000001L
#define D3DPRESENTFLAG_WIDESCREEN            0x00000010L
#define D3DPRESENTFLAG_INTERLACED            0x00000020L
#define D3DPRESENTFLAG_PROGRESSIVE           0x00000040L
#define D3DPRESENTFLAG_FIELD                 0x00000080L
#define D3DPRESENTFLAG_10X11PIXELASPECTRATIO 0x00000100L
#define D3DPRESENTFLAG_EMULATE_REFRESH_RATE  0x00000200L 

#define D3DPRESENT_RATE_UNLIMITED            0x00000000L
#define D3DPRESENT_RATE_DEFAULT              D3DPRESENT_RATE_UNLIMITED

typedef struct _D3DDISPLAYMODE {
    UINT            Width;
    UINT            Height;
    UINT            RefreshRate;
    DWORD           Flags;
    D3DFORMAT       Format;
} D3DDISPLAYMODE;

typedef enum _D3DDEVTYPE {
    D3DDEVTYPE_HAL         = 1,
    D3DDEVTYPE_REF         = 2,
    D3DDEVTYPE_SW          = 3,

    D3DDEVTYPE_FORCE_DWORD = 0x7fffffff
} D3DDEVTYPE;

typedef enum _D3DRESOURCETYPE {
    D3DRTYPE_NONE           =  0,
    D3DRTYPE_SURFACE        =  1,
    D3DRTYPE_VOLUME         =  2,
    D3DRTYPE_TEXTURE        =  3,
    D3DRTYPE_VOLUMETEXTURE  =  4,
    D3DRTYPE_CUBETEXTURE    =  5,
    D3DRTYPE_VERTEXBUFFER   =  6,
    D3DRTYPE_INDEXBUFFER    =  7,
    D3DRTYPE_PUSHBUFFER     =  8,
    D3DRTYPE_PALETTE        =  9,
    D3DRTYPE_FIXUP          =  10,

    D3DRTYPE_FORCE_DWORD    = 0x7fffffff
} D3DRESOURCETYPE;

typedef enum _D3DUSAGE {
    D3DUSAGE_RENDERTARGET           = 0x00000001,
    D3DUSAGE_DEPTHSTENCIL           = 0x00000002,
    D3DUSAGE_WRITEONLY              = 0x00000008,
    D3DUSAGE_POINTS                 = 0x00000040,
    D3DUSAGE_RTPATCHES              = 0x00000080,
    D3DUSAGE_DYNAMIC                = 0x00000200,

    D3DUSAGE_BORDERSOURCE_TEXTURE   = 0x00000000,
    D3DUSAGE_BORDERSOURCE_COLOR     = 0x00000008,
} D3DUSAGE;

typedef enum _D3DCUBEMAP_FACES {
    D3DCUBEMAP_FACE_POSITIVE_X  = 0,
    D3DCUBEMAP_FACE_NEGATIVE_X  = 1,
    D3DCUBEMAP_FACE_POSITIVE_Y  = 2,
    D3DCUBEMAP_FACE_NEGATIVE_Y  = 3,
    D3DCUBEMAP_FACE_POSITIVE_Z  = 4,
    D3DCUBEMAP_FACE_NEGATIVE_Z  = 5,

    D3DCUBEMAP_FACE_FORCE_DWORD = 0x7fffffff
} D3DCUBEMAP_FACES;

typedef enum _D3DMULTISAMPLE_TYPE {
    D3DMULTISAMPLE_NONE                                     = 0x00110000,
    D3DMULTISAMPLE_2_SAMPLES_MULTISAMPLE_LINEAR             = 0x10210000,
    D3DMULTISAMPLE_2_SAMPLES_MULTISAMPLE_QUINCUNX           = 0x11210000,
    D3DMULTISAMPLE_2_SAMPLES_SUPERSAMPLE_HORIZONTAL_LINEAR  = 0x20210000,
    D3DMULTISAMPLE_2_SAMPLES_SUPERSAMPLE_VERTICAL_LINEAR    = 0x20120000,
    D3DMULTISAMPLE_2_SAMPLES = D3DMULTISAMPLE_2_SAMPLES_MULTISAMPLE_QUINCUNX,
    D3DMULTISAMPLE_4_SAMPLES_MULTISAMPLE_LINEAR             = 0x10220000,
    D3DMULTISAMPLE_4_SAMPLES_MULTISAMPLE_GAUSSIAN           = 0x12220000,
    D3DMULTISAMPLE_4_SAMPLES_SUPERSAMPLE_LINEAR             = 0x20220000,
    D3DMULTISAMPLE_4_SAMPLES_SUPERSAMPLE_GAUSSIAN           = 0x22220000,      
    D3DMULTISAMPLE_4_SAMPLES = D3DMULTISAMPLE_4_SAMPLES_MULTISAMPLE_GAUSSIAN,
    D3DMULTISAMPLE_9_SAMPLES_MULTISAMPLE_GAUSSIAN           = 0x12330000,
    D3DMULTISAMPLE_9_SAMPLES_SUPERSAMPLE_GAUSSIAN           = 0x22330000,
    D3DMULTISAMPLE_9_SAMPLES = D3DMULTISAMPLE_9_SAMPLES_SUPERSAMPLE_GAUSSIAN,
} D3DMULTISAMPLE_TYPE;

typedef enum _D3DMULTISAMPLEMODE {
    D3DMULTISAMPLEMODE_1X                                   = 0,
    D3DMULTISAMPLEMODE_2X                                   = 1,
    D3DMULTISAMPLEMODE_4X                                   = 2,

    D3DMULTISAMPLEMODE_FORCE_DWORD                          = 0x7fffffff
} D3DMULTISAMPLEMODE;

typedef enum _D3DTEXTUREFILTERTYPE {
    D3DTEXF_NONE,         
    D3DTEXF_POINT,      
    D3DTEXF_LINEAR,       
    D3DTEXF_ANISOTROPIC, 
    D3DTEXF_QUINCUNX,    
    D3DTEXF_GAUSSIANCUBIC,

    D3DTEXF_MAX,
    D3DTEXF_FORCE_DWORD = 0x7fffffff,
} D3DTEXTUREFILTERTYPE;

typedef struct _D3DCAPS8 {
    D3DDEVTYPE  DeviceType;
    UINT    AdapterOrdinal;

    DWORD   Caps;
    DWORD   Caps2;
    DWORD   Caps3;
    DWORD   PresentationIntervals;

    DWORD   CursorCaps;

    DWORD   DevCaps;

    DWORD   PrimitiveMiscCaps;
    DWORD   RasterCaps;
    DWORD   ZCmpCaps;
    DWORD   SrcBlendCaps;
    DWORD   DestBlendCaps;
    DWORD   AlphaCmpCaps;
    DWORD   ShadeCaps;
    DWORD   TextureCaps;
    DWORD   TextureFilterCaps;         
    DWORD   CubeTextureFilterCaps;     
    DWORD   VolumeTextureFilterCaps;   
    DWORD   TextureAddressCaps;        
    DWORD   VolumeTextureAddressCaps;  

    DWORD   LineCaps;                 

    DWORD   MaxTextureWidth, MaxTextureHeight;
    DWORD   MaxVolumeExtent;

    DWORD   MaxTextureRepeat;
    DWORD   MaxTextureAspectRatio;
    DWORD   MaxAnisotropy;
    float   MaxVertexW;

    float   GuardBandLeft;
    float   GuardBandTop;
    float   GuardBandRight;
    float   GuardBandBottom;

    float   ExtentsAdjust;
    DWORD   StencilCaps;

    DWORD   FVFCaps;
    DWORD   TextureOpCaps;
    DWORD   MaxTextureBlendStages;
    DWORD   MaxSimultaneousTextures;

    DWORD   VertexProcessingCaps;
    DWORD   MaxActiveLights;
    DWORD   MaxUserClipPlanes;
    DWORD   MaxVertexBlendMatrices;
    DWORD   MaxVertexBlendMatrixIndex;

    float   MaxPointSize;

    DWORD   MaxPrimitiveCount;     
    DWORD   MaxVertexIndex;
    DWORD   MaxStreams;
    DWORD   MaxStreamStride;          

    DWORD   VertexShaderVersion;
    DWORD   MaxVertexShaderConst; 
    DWORD   PixelShaderVersion;
    float   MaxPixelShaderValue;    

} D3DCAPS8;

typedef enum _D3DSWAPEFFECT {
    D3DSWAPEFFECT_DISCARD           = 1,
    D3DSWAPEFFECT_FLIP              = 2,
    D3DSWAPEFFECT_COPY              = 3,
    D3DSWAPEFFECT_COPY_VSYNC        = 4,

    D3DSWAPEFFECT_FORCE_DWORD       = 0x7fffffff
} D3DSWAPEFFECT;

typedef enum _D3DPRESENT_INTERVAL {
    D3DPRESENT_INTERVAL_IMMEDIATE,
    D3DPRESENT_INTERVAL_ONE,
    D3DPRESENT_INTERVAL_ONE_OR_IMMEDIATE,
    D3DPRESENT_INTERVAL_TWO,
    D3DPRESENT_INTERVAL_TWO_OR_IMMEDIATE,
    D3DPRESENT_INTERVAL_THREE,
    D3DPRESENT_INTERVAL_THREE_OR_IMMEDIATE,

    D3DPRESENT_INTERVAL_DEFAULT = D3DPRESENT_INTERVAL_IMMEDIATE,
} D3DPRESENT_INTERVAL;

struct IDirect3DSurface8;
typedef struct IDirect3DSurface8 IDirect3DSurface8, *LPDIRECT3DSURFACE8;

typedef struct _D3DPRESENT_PARAMETERS_ {
    // The following three fields must be valid for a display mode returned 
    // from IDirect3D8::EnumAdapterModes.
    UINT                BackBufferWidth;
    UINT                BackBufferHeight;
    D3DFORMAT           BackBufferFormat;
    // Must be 0, 1, or 2. 0 will be treated as 1.
    UINT                BackBufferCount;

    // Currently ignored.
    D3DMULTISAMPLE_TYPE MultiSampleType;
    // Currently ignored.
    D3DSWAPEFFECT       SwapEffect;
    // Ignored, must be NULL.
    HWND                hDeviceWindow;
    // Must be FALSE.
    BOOL                Windowed;
    // Must be FALSE if DepthStencilSurface is non-NULL.
    BOOL                EnableAutoDepthStencil;
    // Must be D3DFMT_D24S8.
    D3DFORMAT           AutoDepthStencilFormat;
    // Must be (D3DCREATE_HARDWARE_VERTEXPROCESSING | 
    //          D3DCREATE_HARDWARE_PUREDEVICE)
    DWORD               Flags;

    // Must be valid for the same display mode as BackBufferWidth,
    // BackBufferHeight, and BackBufferFormat were, or 0.
    UINT                FullScreen_RefreshRateInHz;

    // Must be a valid D3DPRESENT_INTERVAL.
    // D3DPRESENT_INTERVAL_DEFAULT will be treated as 
    // D3DPRESENT_INTERVAL_IMMEDIATE.
    UINT                FullScreen_PresentationInterval;

    // If non-NULL, BufferSurfaces will supply the initial front and back 
    // buffer(s). The lifetime of these will not be managed by D3D, so it is 
    // the user's responsibility to ensure they live at least as long as the
    // device does, and that they are freed if necessary. 
    // If NULL, D3D will create and manage its own framebuffers
    // on device creation. 
    //
    // D3D does not support "mixing" framebuffers,
    // so if BufferSurfaces[0] is non-NULL, BufferSurfaces[1] must be
    // non-NULL. If BackBufferCount == 2, BackBufferSurfaces[2] also must be
    // non-NULL. If BufferSurfaces[0] is NULL, the other surface(s) must
    // be NULL.
    //
    // If non-NULL, all BufferSurfaces must have been created with the same 
    // width, height, and format as specified by BackBufferWidth, 
    // BackBufferHeight, and BackBufferFormat.
    // 
    // BufferSurfaces[0] will be the initial back buffer and therefore the 
    // first surface drawn to. If BackBufferCount < 2, BufferSurfaces[1] will 
    // be the initial front buffer. If BackBufferCount == 2, BufferSurfaces[1]
    // will be the second back buffer, and BufferSurfaces[2] will be the 
    // initial front buffer.
    // 
    // D3D will not present the initial front buffer in either case, so its 
    // contents are irrelevant and will not be drawn.
    //
    // The contiguous memory regions used by all BufferSurfaces *should* be 
    // contiguous with one another (i.e., coming from the same allocation, 
    // and with no gaps in between). 
    // Non-contiguous regions would require either the use of one tile per 
    // surface or the non-use of tiles for framebuffers altogether.
    //
    // As an implementation detail, device creation currently does
    // not handle the case of non-contiguous BufferSurfaces and will fail.
    //
    // DepthStencilSurface need not be contiguous with BufferSurfaces, and it
    // is permitted to be NULL or non-NULL independent of the BufferSurfaces. 
    // If DepthStencilSurface is non-NULL and EnableAutoDepthStencil == TRUE, 
    // device creation will fail. 
    // If non-NULL, DepthStencilSurface must have been created with dimensions
    // at least as large as BackBufferWidth * BackBufferHeight, and its format
    // must be a valid format as given by IDirect3D8::CheckDepthStencilMatch
    // (currently only D3DFMT_D24S8).
    IDirect3DSurface8  *BufferSurfaces[3];
    IDirect3DSurface8  *DepthStencilSurface;

} D3DPRESENT_PARAMETERS;

#define D3DADAPTER_DEFAULT 0

typedef struct tagRECT {
    LONG left;
    LONG top;
    LONG right;
    LONG bottom;
} RECT, *PRECT, *NPRECT, *LPRECT;

typedef struct _D3DLOCKED_RECT {
    INT                 Pitch;
    void*               pBits;
} D3DLOCKED_RECT;

typedef enum _D3DPRIMITIVETYPE {
    D3DPT_POINTLIST             = NV097_SET_BEGIN_END_OP_POINTS,
    D3DPT_LINELIST              = NV097_SET_BEGIN_END_OP_LINES,
    D3DPT_LINELOOP              = NV097_SET_BEGIN_END_OP_LINE_LOOP,
    D3DPT_LINESTRIP             = NV097_SET_BEGIN_END_OP_LINE_STRIP,
    D3DPT_TRIANGLELIST          = NV097_SET_BEGIN_END_OP_TRIANGLES,
    D3DPT_TRIANGLESTRIP         = NV097_SET_BEGIN_END_OP_TRIANGLE_STRIP,
    D3DPT_TRIANGLEFAN           = NV097_SET_BEGIN_END_OP_TRIANGLE_FAN,
    D3DPT_QUADLIST              = NV097_SET_BEGIN_END_OP_QUADS,
    D3DPT_QUADSTRIP             = NV097_SET_BEGIN_END_OP_QUAD_STRIP,
    D3DPT_POLYGON               = NV097_SET_BEGIN_END_OP_POLYGON,
    D3DPT_FORCE_DWORD           = 0x7fffffff,
} D3DPRIMITIVETYPE;

#define D3D_RENDER_MEMORY_ALIGNMENT 64
#define D3DSURFACE_ALIGNMENT        D3D_RENDER_MEMORY_ALIGNMENT
#define D3DVERTEXBUFFER_ALIGNMENT   1
#define D3DTEXTURE_ALIGNMENT        128
#define D3DPUSHBUFFER_ALIGNMENT     4



typedef struct _D3DPixelShaderDef {
   DWORD    PSAlphaInputs[8];         
   DWORD    PSFinalCombinerInputsABCD;
   DWORD    PSFinalCombinerInputsEFG; 
   DWORD    PSConstant0[8];           
   DWORD    PSConstant1[8];           
   DWORD    PSAlphaOutputs[8];        
   DWORD    PSRGBInputs[8];           
   DWORD    PSCompareMode;            
   DWORD    PSFinalCombinerConstant0;  
   DWORD    PSFinalCombinerConstant1;  
   DWORD    PSRGBOutputs[8];          
   DWORD    PSCombinerCount;           
   DWORD    PSTextureModes;            
   DWORD    PSDotMapping;              
   DWORD    PSInputTexture;            

   DWORD    PSC0Mapping;             
   DWORD    PSC1Mapping;             
   DWORD    PSFinalCombinerConstants;
} D3DPIXELSHADERDEF;

typedef enum _D3DSHADEMODE {
    D3DSHADE_FLAT           = NV097_SET_SHADE_MODEL_FLAT,
    D3DSHADE_GOURAUD        = NV097_SET_SHADE_MODEL_SMOOTH,
    D3DSHADE_FORCE_DWORD    = 0x7fffffff,
} D3DSHADEMODE;

typedef enum _D3DFILLMODE {
    D3DFILL_POINT           = NV097_SET_FRONT_POLYGON_MODE_V_POINT,
    D3DFILL_WIREFRAME       = NV097_SET_FRONT_POLYGON_MODE_V_LINE,
    D3DFILL_SOLID           = NV097_SET_FRONT_POLYGON_MODE_V_FILL,
    D3DFILL_FORCE_DWORD     = 0x7fffffff,
} D3DFILLMODE;

typedef enum _D3DBLEND {
    D3DBLEND_ZERO = NV097_SET_BLEND_FUNC_SFACTOR_V_ZERO,
    D3DBLEND_ONE = NV097_SET_BLEND_FUNC_SFACTOR_V_ONE,
    D3DBLEND_SRCCOLOR = NV097_SET_BLEND_FUNC_SFACTOR_V_SRC_COLOR,
    D3DBLEND_INVSRCCOLOR = NV097_SET_BLEND_FUNC_SFACTOR_V_ONE_MINUS_SRC_COLOR,
    D3DBLEND_SRCALPHA = NV097_SET_BLEND_FUNC_SFACTOR_V_SRC_ALPHA,
    D3DBLEND_INVSRCALPHA = NV097_SET_BLEND_FUNC_SFACTOR_V_ONE_MINUS_SRC_ALPHA,
    D3DBLEND_DESTALPHA = NV097_SET_BLEND_FUNC_SFACTOR_V_DST_ALPHA,
    D3DBLEND_INVDESTALPHA = NV097_SET_BLEND_FUNC_SFACTOR_V_ONE_MINUS_DST_ALPHA,
    D3DBLEND_DESTCOLOR = NV097_SET_BLEND_FUNC_SFACTOR_V_DST_COLOR,
    D3DBLEND_INVDESTCOLOR = NV097_SET_BLEND_FUNC_SFACTOR_V_ONE_MINUS_DST_COLOR,
    D3DBLEND_SRCALPHASAT = NV097_SET_BLEND_FUNC_SFACTOR_V_SRC_ALPHA_SATURATE,
    D3DBLEND_CONSTANTCOLOR = NV097_SET_BLEND_FUNC_SFACTOR_V_CONSTANT_COLOR,
    D3DBLEND_INVCONSTANTCOLOR 
        = NV097_SET_BLEND_FUNC_SFACTOR_V_ONE_MINUS_CONSTANT_COLOR,
    D3DBLEND_CONSTANTALPHA = NV097_SET_BLEND_FUNC_SFACTOR_V_CONSTANT_ALPHA,
    D3DBLEND_INVCONSTANTALPHA 
        = NV097_SET_BLEND_FUNC_SFACTOR_V_ONE_MINUS_CONSTANT_ALPHA,

    D3DBLEND_FORCE_DWORD        = 0x7fffffff,
} D3DBLEND;

typedef enum _D3DBLENDOP {
    D3DBLENDOP_ADD               = NV097_SET_BLEND_EQUATION_V_FUNC_ADD,
    D3DBLENDOP_SUBTRACT          = NV097_SET_BLEND_EQUATION_V_FUNC_SUBTRACT,
    D3DBLENDOP_REVSUBTRACT       = NV097_SET_BLEND_EQUATION_V_FUNC_REVERSE_SUBTRACT,
    D3DBLENDOP_MIN               = NV097_SET_BLEND_EQUATION_V_MIN,
    D3DBLENDOP_MAX               = NV097_SET_BLEND_EQUATION_V_MAX,
    D3DBLENDOP_ADDSIGNED         = NV097_SET_BLEND_EQUATION_V_FUNC_ADD_SIGNED,
    D3DBLENDOP_REVSUBTRACTSIGNED = NV097_SET_BLEND_EQUATION_V_FUNC_REVERSE_SUBTRACT_SIGNED,
    D3DBLENDOP_FORCE_DWORD       = 0x7fffffff,
} D3DBLENDOP;

typedef enum _D3DCULL {
    D3DCULL_NONE                = 0,
    D3DCULL_CW                  = NV097_SET_FRONT_FACE_V_CW,
    D3DCULL_CCW                 = NV097_SET_FRONT_FACE_V_CW,
    D3DCULL_FORCE_DWORD         = 0x7fffffff,
} D3DCULL;

typedef enum _D3DFRONT {                
    D3DFRONT_CW                 = NV097_SET_FRONT_FACE_V_CW,
    D3DFRONT_CCW                = NV097_SET_FRONT_FACE_V_CCW,
    D3DFRONT_FORCE_DWORD        = 0x7fffffff,
} D3DFRONT;

typedef enum _D3DCMPFUNC {
    D3DCMP_NEVER                = NV097_SET_SHADOW_COMPARE_FUNC_NEVER,
    D3DCMP_LESS                 = NV097_SET_SHADOW_COMPARE_FUNC_LESS,
    D3DCMP_EQUAL                = NV097_SET_SHADOW_COMPARE_FUNC_EQUAL,
    D3DCMP_LESSEQUAL            = NV097_SET_SHADOW_COMPARE_FUNC_LEQUAL,
    D3DCMP_GREATER              = NV097_SET_SHADOW_COMPARE_FUNC_GREATER,
    D3DCMP_NOTEQUAL             = NV097_SET_SHADOW_COMPARE_FUNC_NOTEQUAL,
    D3DCMP_GREATEREQUAL         = NV097_SET_SHADOW_COMPARE_FUNC_GEQUAL,
    D3DCMP_ALWAYS               = NV097_SET_SHADOW_COMPARE_FUNC_ALWAYS,
    D3DCMP_FORCE_DWORD          = 0x7fffffff,
} D3DCMPFUNC;

typedef enum _D3DSTENCILOP {
    D3DSTENCILOP_KEEP           = NV097_SET_STENCIL_OP_V_KEEP,
    D3DSTENCILOP_ZERO           = NV097_SET_STENCIL_OP_V_ZERO,
    D3DSTENCILOP_REPLACE        = NV097_SET_STENCIL_OP_V_REPLACE,
    D3DSTENCILOP_INCRSAT        = NV097_SET_STENCIL_OP_V_INCRSAT,
    D3DSTENCILOP_DECRSAT        = NV097_SET_STENCIL_OP_V_DECRSAT,
    D3DSTENCILOP_INVERT         = NV097_SET_STENCIL_OP_V_INVERT,
    D3DSTENCILOP_INCR           = NV097_SET_STENCIL_OP_V_INCR,
    D3DSTENCILOP_DECR           = NV097_SET_STENCIL_OP_V_DECR,
    D3DSTENCILOP_FORCE_DWORD    = 0x7fffffff,
} D3DSTENCILOP;

typedef enum _D3DFOGMODE {
    D3DFOG_NONE                 = 0,
    D3DFOG_EXP                  = NV097_SET_FOG_MODE_V_EXP,
    D3DFOG_EXP2                 = NV097_SET_FOG_MODE_V_EXP2,
    D3DFOG_LINEAR               = NV097_SET_FOG_MODE_V_LINEAR,
    D3DFOG_EXP_ABS              = NV097_SET_FOG_MODE_V_EXP_ABS,
    D3DFOG_EXP2_ABS             = NV097_SET_FOG_MODE_V_EXP2_ABS,
    D3DFOG_LINEAR_ABS           = NV097_SET_FOG_MODE_V_LINEAR_ABS,
    D3DFOG_FORCE_DWORD          = 0x7fffffff,
} D3DFOGMODE;

typedef enum _D3DSWATHWIDTH {
    D3DSWATH_8                  = NV097_SET_SWATH_WIDTH_8,
    D3DSWATH_16                 = NV097_SET_SWATH_WIDTH_16,
    D3DSWATH_32                 = NV097_SET_SWATH_WIDTH_32,
    D3DSWATH_64                 = NV097_SET_SWATH_WIDTH_64,
    D3DSWATH_128                = NV097_SET_SWATH_WIDTH_128,
    D3DSWATH_OFF                = NV097_SET_SWATH_WIDTH_OFF,
    D3DSWATH_FORCE_DWORD        = 0x7fffffff,
} D3DSWATHWIDTH;

typedef enum _D3DLOGICOP {
    D3DLOGICOP_NONE             = 0,
    D3DLOGICOP_CLEAR            = NV097_SET_LOGIC_OP_V_CLEAR,
    D3DLOGICOP_AND              = NV097_SET_LOGIC_OP_V_AND,
    D3DLOGICOP_AND_REVERSE      = NV097_SET_LOGIC_OP_V_AND_REVERSE,
    D3DLOGICOP_COPY             = NV097_SET_LOGIC_OP_V_COPY,
    D3DLOGICOP_AND_INVERTED     = NV097_SET_LOGIC_OP_V_AND_INVERTED,
    D3DLOGICOP_NOOP             = NV097_SET_LOGIC_OP_V_NOOP,
    D3DLOGICOP_XOR              = NV097_SET_LOGIC_OP_V_XOR,
    D3DLOGICOP_OR               = NV097_SET_LOGIC_OP_V_OR,
    D3DLOGICOP_NOR              = NV097_SET_LOGIC_OP_V_NOR,
    D3DLOGICOP_EQUIV            = NV097_SET_LOGIC_OP_V_EQUIV,
    D3DLOGICOP_INVERT           = NV097_SET_LOGIC_OP_V_INVERT,
    D3DLOGICOP_OR_REVERSE       = NV097_SET_LOGIC_OP_V_OR_REVERSE,
    D3DLOGICOP_COPY_INVERTED    = NV097_SET_LOGIC_OP_V_COPY_INVERTED,
    D3DLOGICOP_OR_INVERTED      = NV097_SET_LOGIC_OP_V_OR_INVERTED,
    D3DLOGICOP_NAND             = NV097_SET_LOGIC_OP_V_NAND,
    D3DLOGICOP_SET              = NV097_SET_LOGIC_OP_V_SET,
    D3DLOGICOP_FORCE_DWORD      = 0x7fffffff,
} D3DLOGICOP;

typedef enum _D3DVERTEXBLENDFLAGS {
    D3DVBF_DISABLE           = NV097_SET_SKIN_MODE_OFF,
    D3DVBF_1WEIGHTS          = NV097_SET_SKIN_MODE_2G,  
    D3DVBF_2WEIGHTS          = NV097_SET_SKIN_MODE_3G,  
    D3DVBF_3WEIGHTS          = NV097_SET_SKIN_MODE_4G,  
    D3DVBF_2WEIGHTS2MATRICES = NV097_SET_SKIN_MODE_2,  
    D3DVBF_3WEIGHTS3MATRICES = NV097_SET_SKIN_MODE_3,  
    D3DVBF_4WEIGHTS4MATRICES = NV097_SET_SKIN_MODE_4,  

    D3DVBF_MAX               = D3DVBF_4WEIGHTS4MATRICES + 1,
    D3DVBF_FORCE_DWORD       = 0x7fffffff,
} D3DVERTEXBLENDFLAGS;

typedef enum _D3DDEPTHCLIPCONTROL {
    D3DDCC_CULLPRIMITIVE    = 0x00000001, 
    D3DDCC_CLAMP            = 0x00000010,
    D3DDCC_IGNORE_W_SIGN    = 0x00000100,
} D3DDEPTHCLIPCONTROL;

#define D3DCOLORWRITEENABLE_BLUE    NV097_SET_COLOR_MASK_BLUE_WRITE_ENABLE
#define D3DCOLORWRITEENABLE_GREEN   NV097_SET_COLOR_MASK_GREEN_WRITE_ENABLE
#define D3DCOLORWRITEENABLE_RED     NV097_SET_COLOR_MASK_RED_WRITE_ENABLE
#define D3DCOLORWRITEENABLE_ALPHA   NV097_SET_COLOR_MASK_ALPHA_WRITE_ENABLE
#define D3DCOLORWRITEENABLE_ALL \
    (D3DCOLORWRITEENABLE_BLUE | D3DCOLORWRITEENABLE_GREEN | \
     D3DCOLORWRITEENABLE_RED  | D3DCOLORWRITEENABLE_ALPHA)

typedef enum _D3DRENDERSTATETYPE {
    D3DRS_PS_MIN,

    D3DRS_PSALPHAINPUTS0 = D3DRS_PS_MIN, 
    D3DRS_PSALPHAINPUTS1, 
    D3DRS_PSALPHAINPUTS2, 
    D3DRS_PSALPHAINPUTS3, 
    D3DRS_PSALPHAINPUTS4, 
    D3DRS_PSALPHAINPUTS5, 
    D3DRS_PSALPHAINPUTS6, 
    D3DRS_PSALPHAINPUTS7, 
    D3DRS_PSFINALCOMBINERINPUTSABCD, 
    D3DRS_PSFINALCOMBINERINPUTSEFG, 
    D3DRS_PSCONSTANT0_0,
    D3DRS_PSCONSTANT0_1,
    D3DRS_PSCONSTANT0_2,
    D3DRS_PSCONSTANT0_3,
    D3DRS_PSCONSTANT0_4,
    D3DRS_PSCONSTANT0_5,
    D3DRS_PSCONSTANT0_6,
    D3DRS_PSCONSTANT0_7,
    D3DRS_PSCONSTANT1_0,
    D3DRS_PSCONSTANT1_1,
    D3DRS_PSCONSTANT1_2,
    D3DRS_PSCONSTANT1_3,
    D3DRS_PSCONSTANT1_4,
    D3DRS_PSCONSTANT1_5,
    D3DRS_PSCONSTANT1_6,
    D3DRS_PSCONSTANT1_7,
    D3DRS_PSALPHAOUTPUTS0,
    D3DRS_PSALPHAOUTPUTS1,
    D3DRS_PSALPHAOUTPUTS2,
    D3DRS_PSALPHAOUTPUTS3,
    D3DRS_PSALPHAOUTPUTS4,
    D3DRS_PSALPHAOUTPUTS5,
    D3DRS_PSALPHAOUTPUTS6,
    D3DRS_PSALPHAOUTPUTS7,
    D3DRS_PSRGBINPUTS0,
    D3DRS_PSRGBINPUTS1,
    D3DRS_PSRGBINPUTS2,
    D3DRS_PSRGBINPUTS3,
    D3DRS_PSRGBINPUTS4,
    D3DRS_PSRGBINPUTS5,
    D3DRS_PSRGBINPUTS6,
    D3DRS_PSRGBINPUTS7,
    D3DRS_PSCOMPAREMODE,
    D3DRS_PSFINALCOMBINERCONSTANT0,
    D3DRS_PSFINALCOMBINERCONSTANT1,
    D3DRS_PSRGBOUTPUTS0,
    D3DRS_PSRGBOUTPUTS1,
    D3DRS_PSRGBOUTPUTS2,
    D3DRS_PSRGBOUTPUTS3,
    D3DRS_PSRGBOUTPUTS4,
    D3DRS_PSRGBOUTPUTS5,
    D3DRS_PSRGBOUTPUTS6,
    D3DRS_PSRGBOUTPUTS7,
    D3DRS_PSCOMBINERCOUNT,
                                        
    D3DRS_PSDOTMAPPING,
    D3DRS_PSINPUTTEXTURE,

    D3DRS_PS_MAX,

    D3DRS_ZFUNC = D3DRS_PS_MAX,
    D3DRS_ALPHAFUNC,
    D3DRS_ALPHABLENDENABLE,
    D3DRS_ALPHATESTENABLE,
    D3DRS_ALPHAREF,
    D3DRS_SRCBLEND,
    D3DRS_DESTBLEND,
    D3DRS_ZWRITEENABLE,
    D3DRS_DITHERENABLE,
    D3DRS_SHADEMODE,
    D3DRS_COLORWRITEENABLE,
    D3DRS_STENCILZFAIL,
    D3DRS_STENCILPASS,
    D3DRS_STENCILFUNC,
    D3DRS_STENCILREF,
    D3DRS_STENCILMASK,
    D3DRS_STENCILWRITEMASK,
    D3DRS_BLENDOP,
    D3DRS_BLENDCOLOR,
    D3DRS_SWATHWIDTH,
    D3DRS_POLYGONOFFSETZSLOPESCALE,
    D3DRS_POLYGONOFFSETZOFFSET,
    D3DRS_POINTOFFSETENABLE,
    D3DRS_WIREFRAMEOFFSETENABLE,
    D3DRS_SOLIDOFFSETENABLE,
    D3DRS_DEPTHCLIPCONTROL,
    D3DRS_STIPPLEENABLE,

    D3DRS_SIMPLE_MAX,

    D3DRS_FOGENABLE = D3DRS_SIMPLE_MAX,
    D3DRS_FOGTABLEMODE, 
    D3DRS_FOGSTART, 
    D3DRS_FOGEND, 
    D3DRS_FOGDENSITY, 
    D3DRS_RANGEFOGENABLE, 
    D3DRS_WRAP0, 
    D3DRS_WRAP1, 
    D3DRS_WRAP2,
    D3DRS_WRAP3,
    D3DRS_LIGHTING,
    D3DRS_SPECULARENABLE,
    D3DRS_LOCALVIEWER,
    D3DRS_COLORVERTEX,
    D3DRS_BACKSPECULARMATERIALSOURCE,
    D3DRS_BACKDIFFUSEMATERIALSOURCE,
    D3DRS_BACKAMBIENTMATERIALSOURCE,
    D3DRS_BACKEMISSIVEMATERIALSOURCE,
    D3DRS_SPECULARMATERIALSOURCE,
    D3DRS_DIFFUSEMATERIALSOURCE,
    D3DRS_AMBIENTMATERIALSOURCE,
    D3DRS_EMISSIVEMATERIALSOURCE,
    D3DRS_BACKAMBIENT,
    D3DRS_AMBIENT,
    D3DRS_POINTSIZE,
    D3DRS_POINTSIZE_MIN,
    D3DRS_POINTSPRITEENABLE,
    D3DRS_POINTSCALEENABLE,
    D3DRS_POINTSCALE_A,
    D3DRS_POINTSCALE_B,
    D3DRS_POINTSCALE_C,
    D3DRS_POINTSIZE_MAX,
    D3DRS_PATCHEDGESTYLE,
    D3DRS_PATCHSEGMENTS,
    D3DRS_SWAPFILTER,
    D3DRS_PRESENTATIONINTERVAL,

    D3DRS_DEFERRED_MAX,

    D3DRS_PSTEXTUREMODES = D3DRS_DEFERRED_MAX,
    D3DRS_VERTEXBLEND,
    D3DRS_FOGCOLOR,
    D3DRS_FILLMODE,
    D3DRS_BACKFILLMODE,
    D3DRS_TWOSIDEDLIGHTING, 
    D3DRS_NORMALIZENORMALS,
    D3DRS_ZENABLE, 
    D3DRS_STENCILENABLE, 
    D3DRS_STENCILFAIL,
    D3DRS_FRONTFACE,
    D3DRS_CULLMODE,
    D3DRS_TEXTUREFACTOR, 
    D3DRS_ZBIAS, //
    D3DRS_LOGICOP,
    D3DRS_EDGEANTIALIAS,
    D3DRS_MULTISAMPLEANTIALIAS,
    D3DRS_MULTISAMPLEMASK,
    D3DRS_MULTISAMPLEMODE, //
    D3DRS_MULTISAMPLERENDERTARGETMODE, //
    D3DRS_SHADOWFUNC,
    D3DRS_LINEWIDTH,
    D3DRS_SAMPLEALPHA, //
    D3DRS_DXT1NOISEENABLE,
    D3DRS_YUVENABLE, //
    D3DRS_OCCLUSIONCULLENABLE,
    D3DRS_STENCILCULLENABLE,
    D3DRS_ROPZCMPALWAYSREAD,
    D3DRS_ROPZREAD,
    D3DRS_DONOTCULLUNCOMPRESSED,

    D3DRS_MAX,

    D3DRS_FORCE_DWORD                   = 0x7fffffff,
} D3DRENDERSTATETYPE;

enum PS_CHANNEL {
    PS_CHANNEL_RGB      = 0x00,
    PS_CHANNEL_BLUE     = 0x00,
    PS_CHANNEL_ALPHA    = 0x10,
};

enum PS_INPUTMAPPING {
    PS_INPUTMAPPING_UNSIGNED_IDENTITY = 
        NV097_SET_COMBINER_ALPHA_ICW_A_MAP_UNSIGNED_IDENTITY,
    PS_INPUTMAPPING_UNSIGNED_INVERT = 
        (NV097_SET_COMBINER_ALPHA_ICW_A_MAP_UNSIGNED_INVERT * 2) << 4,
    PS_INPUTMAPPING_EXPAND_NORMAL = 
        (NV097_SET_COMBINER_ALPHA_ICW_A_MAP_EXPAND_NORMAL   * 2) << 4, 
    PS_INPUTMAPPING_EXPAND_NEGATE  = 
        (NV097_SET_COMBINER_ALPHA_ICW_A_MAP_EXPAND_NEGATE   * 2) << 4, 
    PS_INPUTMAPPING_HALFBIAS_NORMAL = 
        (NV097_SET_COMBINER_ALPHA_ICW_A_MAP_HALFBIAS_NORMAL * 2) << 4,
    PS_INPUTMAPPING_HALFBIAS_NEGATE = 
        (NV097_SET_COMBINER_ALPHA_ICW_A_MAP_HALFBIAS_NEGATE * 2) << 4,
    PS_INPUTMAPPING_SIGNED_IDENTITY = 
        (NV097_SET_COMBINER_ALPHA_ICW_A_MAP_SIGNED_IDENTITY * 2) << 4, 
    PS_INPUTMAPPING_SIGNED_NEGATE = 
        (NV097_SET_COMBINER_ALPHA_ICW_A_MAP_SIGNED_NEGATE   * 2) << 4,
};

enum PS_REGISTER {
    PS_REGISTER_ZERO        = 0x00,
    PS_REGISTER_DISCARD     = 0x00,
    PS_REGISTER_C0          = 0x01,
    PS_REGISTER_C1          = 0x02,
    PS_REGISTER_FOG         = 0x03,
    PS_REGISTER_V0          = 0x04,
    PS_REGISTER_V1          = 0x05,
    PS_REGISTER_T0          = 0x08,
    PS_REGISTER_T1          = 0x09,
    PS_REGISTER_T2          = 0x0A,
    PS_REGISTER_T3          = 0x0B,
    PS_REGISTER_R0          = 0x0C,
    PS_REGISTER_R1          = 0x0D,
    PS_REGISTER_V1R0_SUM    = 0x0E,
    PS_REGISTER_EF_PROD     = 0x0F,

    PS_REGISTER_ONE = 
        PS_REGISTER_ZERO | PS_INPUTMAPPING_UNSIGNED_INVERT,
    PS_REGISTER_NEGATIVE_ONE = 
        PS_REGISTER_ZERO | PS_INPUTMAPPING_EXPAND_NORMAL,
    PS_REGISTER_ONE_HALF = 
        PS_REGISTER_ZERO | PS_INPUTMAPPING_HALFBIAS_NEGATE,
    PS_REGISTER_NEGATIVE_ONE_HALF = 
        PS_REGISTER_ZERO | PS_INPUTMAPPING_HALFBIAS_NORMAL,
};

typedef struct _D3DVIEWPORT8 {
    DWORD       X;
    DWORD       Y;
    DWORD       Width;
    DWORD       Height;
    float       MinZ;
    float       MaxZ;
} D3DVIEWPORT8;

typedef struct {
    DWORD StreamIndex;
    DWORD Offset;
    DWORD Format;
    BYTE TessType;
    BYTE TessSource;
} D3DVERTEXSHADERINPUT;

typedef struct {
    D3DVERTEXSHADERINPUT Input[16];
} D3DVERTEXATTRIBUTEFORMAT;

struct IDirect3DVertexBuffer8;
typedef struct IDirect3DVertexBuffer8 IDirect3DVertexBuffer8, 
                                      *LPDIRECT3DVERTEXBUFFER8;
typedef struct _D3DSTREAM_INPUT { 
    LPDIRECT3DVERTEXBUFFER8 VertexBuffer;
    UINT Stride;
    UINT Offset;
} D3DSTREAM_INPUT;

typedef struct _D3DSURFACE_DESC {
    D3DFORMAT           Format;
    D3DRESOURCETYPE     Type;
    DWORD               Usage;
    UINT                Size;
    D3DMULTISAMPLE_TYPE MultiSampleType;
    UINT                Width;
    UINT                Height;
} D3DSURFACE_DESC;
                         // elem count                data type
#define D3DVSDT_FLOAT1      ((1 << 4) | NV097_SET_VERTEX_DATA_ARRAY_FORMAT_TYPE_F)
#define D3DVSDT_FLOAT2      ((2 << 4) | NV097_SET_VERTEX_DATA_ARRAY_FORMAT_TYPE_F)
#define D3DVSDT_FLOAT3      ((3 << 4) | NV097_SET_VERTEX_DATA_ARRAY_FORMAT_TYPE_F)
#define D3DVSDT_FLOAT4      ((4 << 4) | NV097_SET_VERTEX_DATA_ARRAY_FORMAT_TYPE_F)
#define D3DVSDT_D3DCOLOR    ((4 << 4) | NV097_SET_VERTEX_DATA_ARRAY_FORMAT_TYPE_UB_D3D) 
#define D3DVSDT_SHORT1      ((1 << 4) | NV097_SET_VERTEX_DATA_ARRAY_FORMAT_TYPE_S32K)
#define D3DVSDT_SHORT2      ((2 << 4) | NV097_SET_VERTEX_DATA_ARRAY_FORMAT_TYPE_S32K)
#define D3DVSDT_SHORT3      ((3 << 4) | NV097_SET_VERTEX_DATA_ARRAY_FORMAT_TYPE_S32K)
#define D3DVSDT_SHORT4      ((4 << 4) | NV097_SET_VERTEX_DATA_ARRAY_FORMAT_TYPE_S32K)

#define D3DVSDT_NORMSHORT1  ((1 << 4) | NV097_SET_VERTEX_DATA_ARRAY_FORMAT_TYPE_S1) 
#define D3DVSDT_NORMSHORT2  ((2 << 4) | NV097_SET_VERTEX_DATA_ARRAY_FORMAT_TYPE_S1) 
#define D3DVSDT_NORMSHORT3  ((3 << 4) | NV097_SET_VERTEX_DATA_ARRAY_FORMAT_TYPE_S1) 
#define D3DVSDT_NORMSHORT4  ((4 << 4) | NV097_SET_VERTEX_DATA_ARRAY_FORMAT_TYPE_S1) 
#define D3DVSDT_NORMPACKED3 ((1 << 4) | NV097_SET_VERTEX_DATA_ARRAY_FORMAT_TYPE_CMP)

#define D3DVSDT_PBYTE1      ((1 << 4) | NV097_SET_VERTEX_DATA_ARRAY_FORMAT_TYPE_UB_OGL)
#define D3DVSDT_PBYTE2      ((1 << 4) | NV097_SET_VERTEX_DATA_ARRAY_FORMAT_TYPE_UB_OGL)
#define D3DVSDT_PBYTE3      ((1 << 4) | NV097_SET_VERTEX_DATA_ARRAY_FORMAT_TYPE_UB_OGL)
#define D3DVSDT_PBYTE4      ((1 << 4) | NV097_SET_VERTEX_DATA_ARRAY_FORMAT_TYPE_UB_OGL)
#define D3DVSDT_FLOAT2H     ((7 << 4) | NV097_SET_VERTEX_DATA_ARRAY_FORMAT_TYPE_F)     
                                                                                    
#define D3DVSDT_NONE        (    0    | NV097_SET_VERTEX_DATA_ARRAY_FORMAT_TYPE_F)     

// pixel/vertex shader end token
#define D3DPS_END()  0x0000FFFF
#define D3DVS_END()  0x0000FFFF

typedef enum D3DPOOL {
    D3DPOOL_DEFAULT = 0,
    D3DPOOL_MANAGED = 1,
    D3DPOOL_SYSTEMMEM = 2,
    D3DPOOL_SCRATCH = 3,

    D3DPOOL_FORCE_DWORD = 0x7fffffff,
} D3DPOOL;

typedef enum _D3DTEXTURESTAGESTATETYPE {
    D3DTSS_ADDRESSU,  
    D3DTSS_ADDRESSV,  
    D3DTSS_ADDRESSW,  
    D3DTSS_MAGFILTER,  
    D3DTSS_MINFILTER,  
    D3DTSS_MIPFILTER,  
    D3DTSS_MIPMAPLODBIAS,  
    D3DTSS_MAXMIPLEVEL,  
    D3DTSS_MAXANISOTROPY,  
    D3DTSS_COLORKEYOP,  
    D3DTSS_COLORSIGN,  
    D3DTSS_ALPHAKILL,  

    D3DTSS_DEFERRED_TEXTURE_STATE_MAX,

    D3DTSS_COLOROP = D3DTSS_DEFERRED_TEXTURE_STATE_MAX,  
    D3DTSS_COLORARG0,  
    D3DTSS_COLORARG1,  
    D3DTSS_COLORARG2,  
    D3DTSS_ALPHAOP,  
    D3DTSS_ALPHAARG0,  
    D3DTSS_ALPHAARG1,  
    D3DTSS_ALPHAARG2,  
    D3DTSS_RESULTARG,  
    D3DTSS_TEXTURETRANSFORMFLAGS,  

    D3DTSS_DEFERRED_MAX,

    D3DTSS_BUMPENVMAT00 = D3DTSS_DEFERRED_MAX,  
    D3DTSS_BUMPENVMAT01,  
    D3DTSS_BUMPENVMAT11,  
    D3DTSS_BUMPENVMAT10,  
    D3DTSS_BUMPENVLSCALE,  
    D3DTSS_BUMPENVLOFFSET,  
    D3DTSS_TEXCOORDINDEX,  
    D3DTSS_BORDERCOLOR,  
    D3DTSS_COLORKEYCOLOR,
                                 
    D3DTSS_MAX,
    D3DTSS_FORCE_DWORD           = 0x7fffffff,
} D3DTEXTURESTAGESTATETYPE;

#define D3DTSS_MAXSTAGES 4

#define PS_COMBINERINPUTS(a,b,c,d) ((DWORD)(((a)<<24)|((b)<<16)|((c)<<8)|(d)))
#define PS_COMBINEROUTPUTS(ab,cd,mux_sum,flags) \
    ((DWORD)(((flags)<<12)|((mux_sum)<<8)|((ab)<<4)|(cd)))

enum PS_COMBINEROUTPUT {
    PS_COMBINEROUTPUT_IDENTITY =            
        NV097_SET_COMBINER_ALPHA_OCW_OP_NOSHIFT,
    PS_COMBINEROUTPUT_BIAS =                
        NV097_SET_COMBINER_ALPHA_OCW_OP_NOSHIFT_BIAS,
    PS_COMBINEROUTPUT_SHIFTLEFT_1 =         
        NV097_SET_COMBINER_ALPHA_OCW_OP_SHIFTLEFTBY1,
    PS_COMBINEROUTPUT_SHIFTLEFT_1_BIAS =    
        NV097_SET_COMBINER_ALPHA_OCW_OP_SHIFTLEFTBY1_BIAS,
    PS_COMBINEROUTPUT_SHIFTLEFT_2 =        
         NV097_SET_COMBINER_ALPHA_OCW_OP_SHIFTLEFTBY2,
    PS_COMBINEROUTPUT_SHIFTRIGHT_1 =        
        NV097_SET_COMBINER_ALPHA_OCW_OP_SHIFTRIGHTBY1,

    PS_COMBINEROUTPUT_AB_BLUE_TO_ALPHA =    
        (NV097_SET_COMBINER_COLOR_OCW_BLUETOALPHA_AB >> 12) & 0x80,

    PS_COMBINEROUTPUT_CD_BLUE_TO_ALPHA =    
        NV097_SET_COMBINER_COLOR_OCW_BLUETOALPHA_CD >> 12,

    PS_COMBINEROUTPUT_AB_MULTIPLY = 0x00,
    PS_COMBINEROUTPUT_AB_DOT_PRODUCT =      
        NV097_SET_COMBINER_COLOR_OCW_AB_DOT_ENABLE >> 12,

    PS_COMBINEROUTPUT_CD_MULTIPLY = 0x00,
    PS_COMBINEROUTPUT_CD_DOT_PRODUCT =      
        NV097_SET_COMBINER_COLOR_OCW_CD_DOT_ENABLE >> 12,

    PS_COMBINEROUTPUT_AB_CD_SUM = 0x00,
    PS_COMBINEROUTPUT_AB_CD_MUX =           
        NV097_SET_COMBINER_COLOR_OCW_MUX_ENABLE >> 12,
};

#define PS_COMBINERCOUNT(count, flags) ((DWORD)(((flags)<<8)|(count)))

typedef enum _PS_COMBINERCOUNTFLAGS {
    PS_COMBINERCOUNT_MUX_LSB    = 0x0000,
    PS_COMBINERCOUNT_MUX_MSB    = 0x0001,

    PS_COMBINERCOUNT_SAME_C0    = 0x0000,
    PS_COMBINERCOUNT_UNIQUE_C0  = 0x0010,

    PS_COMBINERCOUNT_SAME_C1    = 0x0000,
    PS_COMBINERCOUNT_UNIQUE_C1  = 0x0100
} PS_COMBINERCOUNTFLAGS;

#define PS_INPUTTEXTURE(t0,t1,t2,t3) ((DWORD)(((t3)<<20)|((t2)<<16)))

#define PS_TEXTUREMODES(t0,t1,t2,t3) \
    ((DWORD)(((t3)<<15)|((t2)<<10)|((t1)<<5)|(t0)))
enum PS_TEXTUREMODES {
    PS_TEXTUREMODES_NONE                 
        = NV097_SET_SHADER_STAGE_PROGRAM_STAGE3_PROGRAM_NONE,
    PS_TEXTUREMODES_PROJECT2D            
        = NV097_SET_SHADER_STAGE_PROGRAM_STAGE3_2D_PROJECTIVE, 
    PS_TEXTUREMODES_PROJECT3D            
        = NV097_SET_SHADER_STAGE_PROGRAM_STAGE3_3D_PROJECTIVE, 
    PS_TEXTUREMODES_CUBEMAP              
        = NV097_SET_SHADER_STAGE_PROGRAM_STAGE3_CUBE_MAP, 
    PS_TEXTUREMODES_PASSTHRU             
        = NV097_SET_SHADER_STAGE_PROGRAM_STAGE3_PASS_THROUGH, 
    PS_TEXTUREMODES_CLIPPLANE            
        = NV097_SET_SHADER_STAGE_PROGRAM_STAGE3_CLIP_PLANE, 
    PS_TEXTUREMODES_BUMPENVMAP           
        = NV097_SET_SHADER_STAGE_PROGRAM_STAGE3_BUMPENVMAP, 
    PS_TEXTUREMODES_BUMPENVMAP_LUM       
        = NV097_SET_SHADER_STAGE_PROGRAM_STAGE3_BUMPENVMAP_LUMINANCE, 
    PS_TEXTUREMODES_BRDF                 
        = NV097_SET_SHADER_STAGE_PROGRAM_STAGE3_BRDF, 
    PS_TEXTUREMODES_DOT_ST               
        = NV097_SET_SHADER_STAGE_PROGRAM_STAGE3_DOT_ST, 
    PS_TEXTUREMODES_DOT_ZW               
        = NV097_SET_SHADER_STAGE_PROGRAM_STAGE3_DOT_ZW,
    PS_TEXTUREMODES_DOT_RFLCT_DIFF       
        = NV097_SET_SHADER_STAGE_PROGRAM_STAGE3_DOT_REFLECT_DIFFUSE, 
    PS_TEXTUREMODES_DOT_RFLCT_SPEC       
        = NV097_SET_SHADER_STAGE_PROGRAM_STAGE3_DOT_REFLECT_SPECULAR, 
    PS_TEXTUREMODES_DOT_STR_3D           
        = NV097_SET_SHADER_STAGE_PROGRAM_STAGE3_DOT_STR_3D, 
    PS_TEXTUREMODES_DOT_STR_CUBE         
        = NV097_SET_SHADER_STAGE_PROGRAM_STAGE3_DOT_STR_CUBE, 
    PS_TEXTUREMODES_DPNDNT_AR            
        = NV097_SET_SHADER_STAGE_PROGRAM_STAGE3_DEPENDENT_AR, 
    PS_TEXTUREMODES_DPNDNT_GB            
        = NV097_SET_SHADER_STAGE_PROGRAM_STAGE3_DEPENDENT_GB, 
    PS_TEXTUREMODES_DOTPRODUCT           
        = NV097_SET_SHADER_STAGE_PROGRAM_STAGE3_DOT_PRODUCT, 
    PS_TEXTUREMODES_DOT_RFLCT_SPEC_CONST 
        = NV097_SET_SHADER_STAGE_PROGRAM_STAGE3_DOT_REFLECT_SPECULAR_CONST
};

#define D3DCLEAR_ZBUFFER    NV097_CLEAR_SURFACE_Z      
#define D3DCLEAR_STENCIL    NV097_CLEAR_SURFACE_STENCIL
#define D3DCLEAR_ZSTENCIL   NV097_CLEAR_SURFACE_ZSTENCIL

#define D3DCLEAR_TARGET     NV097_CLEAR_SURFACE_COLOR
#define D3DCLEAR_TARGET_R   NV097_CLEAR_SURFACE_R
#define D3DCLEAR_TARGET_G   NV097_CLEAR_SURFACE_G
#define D3DCLEAR_TARGET_B   NV097_CLEAR_SURFACE_B
#define D3DCLEAR_TARGET_A   NV097_CLEAR_SURFACE_A

#define D3DZ_MAX_D16        65535.0
#define D3DZ_MAX_D24S8      16777215.0
#define D3DZ_MAX_F16        511.9375

typedef DWORD D3DCOLOR;
#define D3DCOLOR_ARGB(a,r,g,b) \
    ((D3DCOLOR)((((a)&0xff)<<24)|(((r)&0xff)<<16)|(((g)&0xff)<<8)|((b)&0xff)))
#define D3DCOLOR_RGBA(r,g,b,a) D3DCOLOR_ARGB(a,r,g,b)
#define D3DCOLOR_XRGB(r,g,b)   D3DCOLOR_ARGB(0xff,r,g,b)

typedef struct _D3DRECT {
    LONG x1;
    LONG y1;
    LONG x2;
    LONG y2;
} D3DRECT;

#define D3DSCISSORS_MAX 8

#define D3DTILE_MAXTILES            8
#define D3DTILE_MAXTAGS             76800
#define D3DTILE_TAGSIZE             64
#define D3DTILE_ALIGNMENT           0x4000

#define D3DTILE_ZENDTAG(pTile) \
    ((((pTile)->ZStartTag + ((pTile)->Size / D3DTILE_TAGSIZE)) + 255) & ~255)

#define D3DTILE_FLAGS_ZBUFFER       0x00000001
#define D3DTILE_FLAGS_ZCOMPRESS     0x80000000
#define D3DTILE_FLAGS_Z32BITS       0x04000000
#define D3DTILE_FLAGS_Z16BITS       0x00000000

#define D3DTILE_PITCH_0200          0x0200
#define D3DTILE_PITCH_0300          0x0300
#define D3DTILE_PITCH_0400          0x0400
#define D3DTILE_PITCH_0500          0x0500
#define D3DTILE_PITCH_0600          0x0600
#define D3DTILE_PITCH_0700          0x0700
#define D3DTILE_PITCH_0800          0x0800
#define D3DTILE_PITCH_0A00          0x0A00
#define D3DTILE_PITCH_0C00          0x0C00
#define D3DTILE_PITCH_0E00          0x0E00
#define D3DTILE_PITCH_1000          0x1000
#define D3DTILE_PITCH_1400          0x1400
#define D3DTILE_PITCH_1800          0x1800
#define D3DTILE_PITCH_1C00          0x1C00
#define D3DTILE_PITCH_2000          0x2000
#define D3DTILE_PITCH_2800          0x2800
#define D3DTILE_PITCH_3000          0x3000
#define D3DTILE_PITCH_3800          0x3800
#define D3DTILE_PITCH_4000          0x4000
#define D3DTILE_PITCH_5000          0x5000
#define D3DTILE_PITCH_6000          0x6000
#define D3DTILE_PITCH_7000          0x7000
#define D3DTILE_PITCH_8000          0x8000
#define D3DTILE_PITCH_A000          0xA000
#define D3DTILE_PITCH_C000          0xC000
#define D3DTILE_PITCH_E000          0xE000

typedef struct _D3DTILE {                   
    DWORD   Flags;
    void*   pMemory;
    DWORD   Size;
    DWORD   Pitch;
    DWORD   ZStartTag; 
    DWORD   ZOffset;
} D3DTILE;

#define D3DTILE_INDEX_FRAMEBUFFER   0
#define D3DTILE_INDEX_DEPTHSTENCIL  1
#define D3DTILE_INDEX_MAX           8

typedef enum _D3DTEXTUREADDRESS {
    D3DTADDRESS_WRAP            = NV097_SET_TEXTURE_ADDRESS_U_WRAP,
    D3DTADDRESS_MIRROR          = NV097_SET_TEXTURE_ADDRESS_U_MIRROR,
    D3DTADDRESS_CLAMP           = NV097_SET_TEXTURE_ADDRESS_U_CLAMP,
    D3DTADDRESS_BORDER          = NV097_SET_TEXTURE_ADDRESS_U_BORDER,
    D3DTADDRESS_CLAMPTOEDGE     = NV097_SET_TEXTURE_ADDRESS_U_CLAMP_TO_EDGE,
    D3DTADDRESS_MAX,
    D3DTADDRESS_FORCE_DWORD     = 0x7fffffff,
} D3DTEXTUREADDRESS;

typedef enum _D3DTEXTURECOLORKEYOP {
    D3DTCOLORKEYOP_DISABLE      = NV097_SET_TEXTURE_CONTROL0_COLOR_KEY_MODE_DISABLE,
    D3DTCOLORKEYOP_ALPHA        = NV097_SET_TEXTURE_CONTROL0_COLOR_KEY_MODE_ALPHA,
    D3DTCOLORKEYOP_RGBA         = NV097_SET_TEXTURE_CONTROL0_COLOR_KEY_MODE_RGBA,
    D3DTCOLORKEYOP_KILL         = NV097_SET_TEXTURE_CONTROL0_COLOR_KEY_MODE_KILL,

    D3DTCOLORKEYOP_MAX,
    D3DTCOLORKEYOP_FORCE_DWORD  = 0x7fffffff,
} D3DTEXTURECOLORKEYOP;

typedef enum _D3DTEXTUREALPHAKILL {
    D3DTALPHAKILL_DISABLE       = 0,
    D3DTALPHAKILL_ENABLE        = NV097_SET_TEXTURE_CONTROL0_ALPHA_KILL_ENABLE,

    D3DTALPHAKILL_FORCE_DWORD   = 0x7fffffff,
} D3DTEXTUREALPHAKILL;

typedef enum _D3DTEXTUREOP
{
    D3DTOP_DISABLE              =  1,
    D3DTOP_SELECTARG1           =  2,
    D3DTOP_SELECTARG2           =  3,
    D3DTOP_MODULATE             =  4,
    D3DTOP_MODULATE2X           =  5,
    D3DTOP_MODULATE4X           =  6,
    D3DTOP_ADD                  =  7,
    D3DTOP_ADDSIGNED            =  8,
    D3DTOP_ADDSIGNED2X          =  9,
    D3DTOP_SUBTRACT             = 10,
    D3DTOP_ADDSMOOTH            = 11,
                            
    D3DTOP_BLENDDIFFUSEALPHA    = 12,
    D3DTOP_BLENDTEXTUREALPHA    = 14,
    D3DTOP_BLENDFACTORALPHA     = 15,

    D3DTOP_BLENDTEXTUREALPHAPM  = 16,
    D3DTOP_BLENDCURRENTALPHA    = 13,

    D3DTOP_PREMODULATE            = 17,   
    D3DTOP_MODULATEALPHA_ADDCOLOR = 18,       
    D3DTOP_MODULATECOLOR_ADDALPHA = 19,                                
    D3DTOP_MODULATEINVALPHA_ADDCOLOR = 20,                             
    D3DTOP_MODULATEINVCOLOR_ADDALPHA = 21,
 
    D3DTOP_DOTPRODUCT3          = 22,

    D3DTOP_MULTIPLYADD          = 23,
    D3DTOP_LERP                 = 24,

    D3DTOP_BUMPENVMAP           = 25,
    D3DTOP_BUMPENVMAPLUMINANCE  = 26,

    D3DTOP_MAX                  = 27,
    D3DTOP_FORCE_DWORD = 0x7fffffff,
} D3DTEXTUREOP;

#define D3DTA_SELECTMASK        0x0000000f 
#define D3DTA_DIFFUSE           0x00000000 
#define D3DTA_CURRENT           0x00000001 
#define D3DTA_TEXTURE           0x00000002 
#define D3DTA_TFACTOR           0x00000003 
#define D3DTA_SPECULAR          0x00000004 
#define D3DTA_TEMP              0x00000005 
#define D3DTA_COMPLEMENT        0x00000010 
#define D3DTA_ALPHAREPLICATE    0x00000020 

#define D3DTA_SELECTMAX         0x00000006
#define D3DTA_MODIFIERMAX       0x00000040

#define D3DTSIGN_ASIGNED        0x10000000
#define D3DTSIGN_AUNSIGNED      0
#define D3DTSIGN_RSIGNED        0x20000000
#define D3DTSIGN_RUNSIGNED      0
#define D3DTSIGN_GSIGNED        0x40000000
#define D3DTSIGN_GUNSIGNED      0
#define D3DTSIGN_BSIGNED        0x80000000
#define D3DTSIGN_BUNSIGNED      0


#endif // NXDK_HAVE_D3D8TYPES
